import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedRectangle1Widget23.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedNextWidget10.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedServiceWidget23.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedVectorWidget84.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedBatteryWidget23.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedCreateauniquepasswordtologinintoyouraccountWidget.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedEnterNewPasswordWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedTimeWidget23.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedRepeatNewPasswordWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedRectangle32Widget17.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedVectorWidget83.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedCreatePasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedRectangle40Widget9.dart';
import 'package:flutterapp/upayapp/generatedpage15createpasswordwidget/generated/GeneratedRectangle41Widget2.dart';

/* Frame Page 15 Create Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage15CreatePasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget23(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget23(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget23(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget23()),
              ),
              Positioned(
                left: 0.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedRectangle32Widget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.056,
                        translateY:
                            constraints.maxHeight * 0.059113300492610835,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget83())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 22.0,
                child: GeneratedCreatePasswordWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 17.0,
                child:
                    GeneratedCreateauniquepasswordtologinintoyouraccountWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 17.0,
                child: GeneratedEnterNewPasswordWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 17.0,
                child: GeneratedRepeatNewPasswordWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle41Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle42Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 29.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 51.0,
                child: GeneratedRectangle40Widget9(),
              ),
              Positioned(
                left: 34.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8773333333333333,
                        translateY: constraints.maxHeight * 0.937192118226601,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget84())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
