import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedGH16900Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedFeesDetailsWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedFEESDETAILSWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget28.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedMRALBERTGBEVEWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedUPAYWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedServiceWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedBatteryWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedPaymentHistoryWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedFeesWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedGraduationFeesWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget26.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget27.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedYourExistingBalanceWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedPSCSC200016Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedTimeWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget31.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget30.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget24.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedLogoutWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedPAYMENTHISTORYWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedResitWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedVectorWidget25.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedPAYWidget.dart';
import 'package:flutterapp/upayapp/generatedpage5mainmenuwidget/generated/GeneratedRectangle21Widget.dart';

/* Frame Page 5 Main Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage5MainMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget5(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget5(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget5()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 2.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 41.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 41.0,
                child: GeneratedRectangle31Widget2(),
              ),
              Positioned(
                left: 215.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 41.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 95.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 92.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 7.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 400.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 65.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 65.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 65.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 65.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 16.0,
                child: GeneratedMRALBERTGBEVEWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 18.0,
                child: GeneratedYourExistingBalanceWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedGH16900Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 27.0,
                child: GeneratedPSCSC200016Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 18.0,
                child: GeneratedPAYWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 15.0,
                child: GeneratedFEESDETAILSWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 15.0,
                child: GeneratedPAYMENTHISTORYWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 89.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 174.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 89.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 89.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 188.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 1.0,
                height: 62.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06933333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 26.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.264,
                        translateY: constraints.maxHeight * 0.4827586206896552,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget24())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05333333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                  double percentHeight = 0.03078817733990148;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.672,
                        translateY: constraints.maxHeight * 0.4753694581280788,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget25())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.072;
                  double scaleX = (constraints.maxWidth * percentWidth) / 27.0;

                  double percentHeight = 0.03694581280788178;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.5923645320197044,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget26())
                  ]);
                }),
              ),
              Positioned(
                left: 98.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 17.0,
                child: GeneratedFeesWidget(),
              ),
              Positioned(
                left: 248.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 17.0,
                child: GeneratedResitWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 14.0,
                child: GeneratedGraduationFeesWidget(),
              ),
              Positioned(
                left: 99.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 12.0,
                child: GeneratedPaymentHistoryWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 15.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05333333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07466666666666667,
                        translateY: constraints.maxHeight * 0.9310344827586207,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget27())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06933333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 26.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.33066666666666666,
                        translateY: constraints.maxHeight * 0.9310344827586207,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget28())
                  ]);
                }),
              ),
              Positioned(
                left: 315.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 15.0,
                child: GeneratedLogoutWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.022167487684729065;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.05295566502463054,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget29())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.022167487684729065;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.9359605911330049,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget30())
                  ]);
                }),
              ),
              Positioned(
                left: 318.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 15.0,
                child: GeneratedLogoutWidget1(),
              ),
              Positioned(
                left: 209.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 12.0,
                child: GeneratedFeesDetailsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.019704433497536946;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 16.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6106666666666667,
                        translateY: constraints.maxHeight * 0.9347290640394089,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget31())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }

  GeneratedPAYMENTHISTORYWidget() => GeneratedPAYMENTHISTORYWidget();

  GeneratedFeesDetailsWidget() => GeneratedFeesDetailsWidget();

  GeneratedPaymentHistoryWidget() {}
}

GeneratedFEESDETAILSWidget() {}
