import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedCancelWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle38Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedConfirmPaymentWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedGbeveAlbertWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle32Widget8.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedYourTransactionWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle1Widget14.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedPersonalDetailsWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle39Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedStudentNumberWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedNextWidget7.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle20Widget9.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedVectorWidget61.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedTimeWidget14.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget10.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedTransferWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedVectorWidget60.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedStudentNameWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/Generated1011Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/Generated0256724911Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedBatteryWidget14.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedGH270000Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedTOUCCResitAccountWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedGraduationFeesWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedTelNoWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedReferenceWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget11.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle24Widget10.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedRectangle37Widget7.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedPayyourGraduationFeeWidget.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedUPAYWidget9.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedPSCSC200016Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage21graduationnextpagewidget/generated/GeneratedServiceWidget14.dart';

/* Frame Page 21 Graduation Next Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage21GraduationNextPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget14(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget14(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget14(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget14()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget9(),
              ),
              Positioned(
                left: -4.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 648.0,
                child: GeneratedRectangle32Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle24Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 77.0,
                child: GeneratedRectangle37Widget7(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget9(),
              ),
              Positioned(
                left: 118.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 57.0,
                child: GeneratedConfirmPaymentWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget10(),
              ),
              Positioned(
                left: 139.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget11(),
              ),
              Positioned(
                left: 197.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle38Widget5(),
              ),
              Positioned(
                left: 9.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle39Widget2(),
              ),
              Positioned(
                left: 211.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget7(),
              ),
              Positioned(
                left: 103.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 19.0,
                child: GeneratedCancelWidget3(),
              ),
              Positioned(
                left: 13.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 17.0,
                child: GeneratedYourTransactionWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9386666666666666,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget60())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.050666666666666665,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget61())
                  ]);
                }),
              ),
              Positioned(
                left: 13.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 16.0,
                child: GeneratedPersonalDetailsWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedTransferWidget2(),
              ),
              Positioned(
                left: 254.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 19.0,
                child: GeneratedGH270000Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 16.0,
                child: GeneratedTOUCCResitAccountWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 16.0,
                child: GeneratedStudentNumberWidget2(),
              ),
              Positioned(
                left: 224.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 19.0,
                child: GeneratedPSCSC200016Widget6(),
              ),
              Positioned(
                left: 13.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 16.0,
                child: GeneratedStudentNameWidget2(),
              ),
              Positioned(
                left: 247.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 16.0,
                child: GeneratedGbeveAlbertWidget2(),
              ),
              Positioned(
                left: 13.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 16.0,
                child: GeneratedTelNoWidget2(),
              ),
              Positioned(
                left: 262.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 19.0,
                child: Generated0256724911Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 19.0,
                child: Generated1011Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 19.0,
                child: GeneratedReferenceWidget4(),
              ),
              Positioned(
                left: 218.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 16.0,
                child: GeneratedGraduationFeesWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 21.0,
                child: GeneratedPayyourGraduationFeeWidget(),
              )
            ]),
      ),
    ));
  }
}
