import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedRectangle1Widget22.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedVectorWidget81.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedRepeatNewPasswordWidget.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedYournewpasswordmustbedifferentfromyouroldpasswordsWidge.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedCreateNewPasswordWidget.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedNextWidget9.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedBatteryWidget22.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedRectangle40Widget8.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedTimeWidget22.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedEnterNewPasswordWidget.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedRectangle32Widget16.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage12changepasswordwidget/generated/GeneratedServiceWidget22.dart';

/* Frame Page 12 Change Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage12ChangePasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget22(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget22(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget22(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget22()),
              ),
              Positioned(
                left: 0.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedRectangle32Widget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.056,
                        translateY:
                            constraints.maxHeight * 0.059113300492610835,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget81())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 22.0,
                child: GeneratedCreateNewPasswordWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 32.0,
                child:
                    GeneratedYournewpasswordmustbedifferentfromyouroldpasswordsWidge(),
              ),
              Positioned(
                left: 21.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 17.0,
                child: GeneratedEnterNewPasswordWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 17.0,
                child: GeneratedRepeatNewPasswordWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle42Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 51.0,
                child: GeneratedRectangle40Widget8(),
              ),
              Positioned(
                left: 34.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8773333333333333,
                        translateY: constraints.maxHeight * 0.937192118226601,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget82())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
