import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedDonthaveanaccountWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedPSCSC200000Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedIcbaselineremoveredeyeWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedTimeWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedWelcomebackLoginwithyourcredentialsWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRegistrationNumberWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedHelloThereWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedVectorWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedServiceWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedFoCOe_QXEAAhV2A1Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedBatteryWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedCarbonpasswordWidget.dart';
import 'package:flutterapp/upayapp/generatedpage1loginsignuppagehidepasswordwidget/generated/GeneratedForgottenPasswordClickHereToResetWidget.dart';

/* Frame Page 1 Login/Sign up Page Hide Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage1LoginSignupPageHidePasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -2.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 798.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: -47.0,
                top: -246.0,
                right: null,
                bottom: null,
                width: 552.0,
                height: 1058.0,
                child: GeneratedFoCOe_QXEAAhV2A1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 401.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 21.0,
                child: GeneratedHelloThereWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedWelcomebackLoginwithyourcredentialsWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 24.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 21.0,
                child: GeneratedRegistrationNumberWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 21.0,
                child: GeneratedDonthaveanaccountWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedForgottenPasswordClickHereToResetWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 26.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 26.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 26.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 26.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.04;

                  final double height =
                      constraints.maxHeight * 0.01847290640394089;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.152,
                        y: constraints.maxHeight * 0.45566502463054187,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 88.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 24.0,
                child: GeneratedPSCSC200000Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 24.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedCarbonpasswordWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.032669102986653646;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      12.250913619995117;

                  double percentHeight = 0.015086206896551725;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 12.25;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.152,
                        translateY: constraints.maxHeight * 0.5221674876847291,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.004666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 1.75;

                  double percentHeight = 0.0021551724137931034;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 1.75;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.173,
                        translateY: constraints.maxHeight * 0.5254002463054187,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget6())
                  ]);
                }),
              ),
              Positioned(
                left: 106.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 40.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 150.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 24.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 275.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget(),
              ),
              Positioned(
                left: null,
                top: 3.0,
                right: 22.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -140.60, y: 0.00, z: 0, child: GeneratedTimeWidget()),
              ),
              Positioned(
                left: 106.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 40.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 141.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 21.0,
                child: GeneratedSIGNUPWidget(),
              ),
              Positioned(
                left: 292.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedIcbaselineremoveredeyeWidget(),
              )
            ]),
      ),
    ));
  }
}
