import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedEnterOTPWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedTimeWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedVectorWidget19.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/Generated4911Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedServiceWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedVectorWidget20.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedVectorWidget18.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedWevesentyoua4digitcodetoWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage11forgotpasswordotpwidget/generated/GeneratedBatteryWidget3.dart';

/* Frame Page 11 Forgot Password OTP
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage11ForgotPasswordOTPWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 705.0,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget3(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget3(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget3()),
              ),
              Positioned(
                left: 0.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.056,
                        translateY: constraints.maxHeight * 0.06896551724137931,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget18())
                  ]);
                }),
              ),
              Positioned(
                left: 13.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedEnterOTPWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 22.0,
                child: GeneratedWevesentyoua4digitcodetoWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 26.0,
                child: Generated4911Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 110.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 290.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02586206896551724;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 21.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8746666666666667,
                        translateY: constraints.maxHeight * 0.07019704433497537,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget19())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 51.0,
                child: GeneratedRectangle40Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8773333333333333,
                        translateY: constraints.maxHeight * 0.937192118226601,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget20())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
