import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedVectorWidget33.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle29Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle26Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedPAYWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedVectorWidget35.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedFEESDETAILSWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedVectorWidget32.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedServiceWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedFeesDetailsWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedUPAYWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedPaymentHistoryWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle33Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedTimeWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedMRALBERTGBEVEWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle34Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedYourExistingBalanceWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle31Widget3.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedBatteryWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedLogoutWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedPSCSC200016Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedVectorWidget36.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedGH16900Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedLogoutWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedPSCSC200016GHs00020660022350022350016900Widget.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedPAYMENTHISTORYWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage20feesdetailswidget/generated/GeneratedStudentFeesRegNumberCurrencyYourExistingbalanceFeesfor2.dart';

/* Frame Page 20 Fees details
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage20FeesdetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget6(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget6(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget6(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget6()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 238.0,
                child: GeneratedRectangle23Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 95.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 92.0,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 2.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 41.0,
                child: GeneratedRectangle33Widget1(),
              ),
              Positioned(
                left: 76.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 41.0,
                child: GeneratedRectangle31Widget3(),
              ),
              Positioned(
                left: 215.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 41.0,
                child: GeneratedRectangle32Widget1(),
              ),
              Positioned(
                left: 95.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 7.0,
                child: GeneratedRectangle25Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 400.0,
                child: GeneratedRectangle24Widget2(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget1(),
              ),
              Positioned(
                left: 109.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 16.0,
                child: GeneratedMRALBERTGBEVEWidget1(),
              ),
              Positioned(
                left: 102.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 18.0,
                child: GeneratedYourExistingBalanceWidget1(),
              ),
              Positioned(
                left: 131.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 18.0,
                child: GeneratedGH16900Widget1(),
              ),
              Positioned(
                left: 95.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 27.0,
                child: GeneratedPSCSC200016Widget1(),
              ),
              Positioned(
                left: 34.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 18.0,
                child: GeneratedPAYWidget1(),
              ),
              Positioned(
                left: 102.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 15.0,
                child: GeneratedFEESDETAILSWidget1(),
              ),
              Positioned(
                left: 223.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 15.0,
                child: GeneratedPAYMENTHISTORYWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 178.0,
                child: GeneratedRectangle26Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 65.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 65.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 65.0,
                child: GeneratedRectangle34Widget1(),
              ),
              Positioned(
                left: 292.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 65.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 99.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 12.0,
                child: GeneratedPaymentHistoryWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 15.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 209.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 12.0,
                child: GeneratedFeesDetailsWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05333333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07466666666666667,
                        translateY: constraints.maxHeight * 0.9310344827586207,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget32())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06933333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 26.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.33066666666666666,
                        translateY: constraints.maxHeight * 0.9310344827586207,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget33())
                  ]);
                }),
              ),
              Positioned(
                left: 44.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 198.0,
                child:
                    GeneratedStudentFeesRegNumberCurrencyYourExistingbalanceFeesfor2(),
              ),
              Positioned(
                left: 38.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 201.0,
                child:
                    GeneratedPSCSC200016GHs00020660022350022350016900Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 1.0,
                height: 126.0,
                child: GeneratedRectangle29Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.019704433497536946;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 16.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6026666666666667,
                        translateY: constraints.maxHeight * 0.9347290640394089,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget34())
                  ]);
                }),
              ),
              Positioned(
                left: 315.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 15.0,
                child: GeneratedLogoutWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.022167487684729065;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.05295566502463054,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget35())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.022167487684729065;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.9359605911330049,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget36())
                  ]);
                }),
              ),
              Positioned(
                left: 318.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 15.0,
                child: GeneratedLogoutWidget3(),
              )
            ]),
      ),
    ));
  }

  GeneratedFeesDetailsWidget1() => GeneratedFeesDetailsWidget1();

  GeneratedPAYMENTHISTORYWidget1() => GeneratedPAYMENTHISTORYWidget1();

  GeneratedFEESDETAILSWidget1() {}

  GeneratedPaymentHistoryWidget1() {}
}
