import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedBatteryWidget11.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedEnteramounttopayWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle38Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedEg1500Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedTimeWidget11.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedEnteryourphonenumberWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle36Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedPSCSC20XXXXWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedMaterialsymbolsarrowbackWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedEnteryourregistrationnumberWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedServiceWidget11.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedPayyourGraduationFeesWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle35Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle1Widget11.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle24Widget7.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedVectorWidget52.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedNextWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedEgJohnDoeWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedEnteryourfullnameWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/Generated0256xxxxxxxWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedUPAYWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle32Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle33Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle34Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle20Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedRectangle37Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage20graduationwidget/generated/GeneratedMaterialsymbolsarrowbackWidget5.dart';

/* Frame Page 20 Graduation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage20GraduationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget11(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget11(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget11(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget11()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 648.0,
                child: GeneratedRectangle32Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle24Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 77.0,
                child: GeneratedRectangle37Widget4(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget6(),
              ),
              Positioned(
                left: 18.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 21.0,
                child: GeneratedPayyourGraduationFeesWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 16.0,
                child: GeneratedEnteryourregistrationnumberWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 16.0,
                child: GeneratedEnteryourfullnameWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 16.0,
                child: GeneratedEnteramounttopayWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 16.0,
                child: GeneratedEnteryourphonenumberWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget4(),
              ),
              Positioned(
                left: 22.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle33Widget5(),
              ),
              Positioned(
                left: 22.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle34Widget5(),
              ),
              Positioned(
                left: 31.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 19.0,
                child: GeneratedPSCSC20XXXXWidget2(),
              ),
              Positioned(
                left: 31.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 16.0,
                child: GeneratedEgJohnDoeWidget2(),
              ),
              Positioned(
                left: 22.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle35Widget5(),
              ),
              Positioned(
                left: 22.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle36Widget4(),
              ),
              Positioned(
                left: 31.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 16.0,
                child: GeneratedEg1500Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 19.0,
                child: Generated0256xxxxxxxWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 51.0,
                child: GeneratedRectangle38Widget2(),
              ),
              Positioned(
                left: 38.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget4(),
              ),
              Positioned(
                left: 139.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.888,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget52())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
