import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedEllipse1Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedYoucannowuseyourStudentNumberandyourPasswordtoLoginWidg.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedTimeWidget20.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedDoneWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedVectorWidget77.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedServiceWidget20.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedRectangle32Widget14.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedRectangle40Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedWhatsAppImage20230314at20592Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedRectangle1Widget20.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedBatteryWidget20.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedVectorWidget78.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedRectangle38Widget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage16accountcreationsuccessfulwidget/generated/GeneratedYourAccounthasbeencreatedWidget.dart';

/* Frame Page 16 Account Creation Successful
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage16AccountCreationSuccessfulWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget20(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget20(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget20(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget20()),
              ),
              Positioned(
                left: -4.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 790.0,
                child: GeneratedRectangle32Widget14(),
              ),
              Positioned(
                left: 68.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 76.0,
                child: GeneratedYourAccounthasbeencreatedWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 46.0,
                child:
                    GeneratedYoucannowuseyourStudentNumberandyourPasswordtoLoginWidg(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedWhatsAppImage20230314at20592Widget4(),
              ),
              Positioned(
                left: 145.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 85.0,
                child: GeneratedEllipse1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.312;
                  double scaleX = (constraints.maxWidth * percentWidth) / 117.0;

                  double percentHeight = 0.1440886699507389;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 117.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.344,
                        translateY: constraints.maxHeight * 0.16009852216748768,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget77())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 81.0,
                child: GeneratedRectangle40Widget6(),
              ),
              Positioned(
                left: 24.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 51.0,
                child: GeneratedRectangle38Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9386666666666666,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget78())
                  ]);
                }),
              ),
              Positioned(
                left: 55.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedDoneWidget4(),
              )
            ]),
      ),
    ));
  }
}
