import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedPasswordWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedLOGINWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedCarbonpasswordWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedForgottenPasswordClickHereToResetWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedSIGNUPWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedDonthaveanaccountWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedBatteryWidget25.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedServiceWidget25.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedPSCSC200000Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedTimeWidget25.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle1Widget25.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedVectorWidget91.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedWelcomebackLoginwithyourcredentialsWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedUniversityofCapeCoastLogo1Widget.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedGroupWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedVectorWidget90.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedHelloThereWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage2welcomepagewidget/generated/GeneratedRegistrationNumberWidget2.dart';

/* Frame Page 2 Welcome Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage2WelcomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 793.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget25(),
              ),
              Positioned(
                left: 118.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 21.0,
                child: GeneratedHelloThereWidget2(),
              ),
              Positioned(
                left: 49.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedWelcomebackLoginwithyourcredentialsWidget2(),
              ),
              Positioned(
                left: 50.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 24.0,
                child: GeneratedPasswordWidget2(),
              ),
              Positioned(
                left: 50.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedRegistrationNumberWidget2(),
              ),
              Positioned(
                left: 113.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedDonthaveanaccountWidget2(),
              ),
              Positioned(
                left: 56.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedForgottenPasswordClickHereToResetWidget2(),
              ),
              Positioned(
                left: 88.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 26.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 49.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 26.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 49.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 26.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 49.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 26.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.04;

                  final double height =
                      constraints.maxHeight * 0.01847290640394089;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.152,
                        y: constraints.maxHeight * 0.45566502463054187,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 88.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 24.0,
                child: GeneratedPSCSC200000Widget2(),
              ),
              Positioned(
                left: 88.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 24.0,
                child: GeneratedWidget5(),
              ),
              Positioned(
                left: 49.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedCarbonpasswordWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.032669102986653646;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      12.250913619995117;

                  double percentHeight = 0.015086206896551725;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 12.25;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.152,
                        translateY: constraints.maxHeight * 0.5221674876847291,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget90())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.004666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 1.75;

                  double percentHeight = 0.0021551724137931034;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 1.75;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.173,
                        translateY: constraints.maxHeight * 0.5254002463054187,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget91())
                  ]);
                }),
              ),
              Positioned(
                left: 106.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 40.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 106.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 40.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 150.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 24.0,
                child: GeneratedLOGINWidget2(),
              ),
              Positioned(
                left: 141.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 21.0,
                child: GeneratedSIGNUPWidget3(),
              ),
              Positioned(
                left: 153.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 103.0,
                child: GeneratedUniversityofCapeCoastLogo1Widget(),
              ),
              Positioned(
                left: 281.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget25(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 13.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget25(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -159.60, y: 0.00, z: 0, child: GeneratedTimeWidget25()),
              )
            ]),
      ),
    ));
  }
}
