import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedEnteryourregistrationnumberWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedMaterialsymbolsarrowbackWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedUPAYWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/Generated0256xxxxxxxWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle35Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle32Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle34Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedEnteramounttopayWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle24Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle20Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle1Widget10.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedPayyourResitRegistrationWidget.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedEnteryourfullnameWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedBatteryWidget10.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedTimeWidget10.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedVectorWidget50.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle36Widget3.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle33Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedNextWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedServiceWidget10.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedPSCSC20XXXXWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedEg1500Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedRectangle37Widget3.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedEnteryourphonenumberWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedEgJohnDoeWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage17resitregistrationwidget/generated/GeneratedMaterialsymbolsarrowbackWidget3.dart';

/* Frame Page 17 Resit Registration
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage17ResitRegistrationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget10(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget10(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget10(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget10()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 648.0,
                child: GeneratedRectangle32Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle24Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 77.0,
                child: GeneratedRectangle37Widget3(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget5(),
              ),
              Positioned(
                left: 18.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 21.0,
                child: GeneratedPayyourResitRegistrationWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 16.0,
                child: GeneratedEnteryourregistrationnumberWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 16.0,
                child: GeneratedEnteryourfullnameWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 16.0,
                child: GeneratedEnteramounttopayWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 16.0,
                child: GeneratedEnteryourphonenumberWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget2(),
              ),
              Positioned(
                left: 22.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle33Widget4(),
              ),
              Positioned(
                left: 22.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle34Widget4(),
              ),
              Positioned(
                left: 31.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 19.0,
                child: GeneratedPSCSC20XXXXWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 16.0,
                child: GeneratedEgJohnDoeWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle35Widget4(),
              ),
              Positioned(
                left: 22.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 41.0,
                child: GeneratedRectangle36Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 16.0,
                child: GeneratedEg1500Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 19.0,
                child: Generated0256xxxxxxxWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 51.0,
                child: GeneratedRectangle38Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget3(),
              ),
              Positioned(
                left: 139.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.888,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget50())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
