import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedStudentNameWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedStudentNumberWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget8.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedTelNoWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedTransferWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedGH270000Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedTOUCCResitAccountWidget.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedResitRegistrationWidget.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle37Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedUPAYWidget8.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedCancelWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/Generated0256724911Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedTimeWidget13.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedNextWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedVectorWidget57.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedVectorWidget58.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedReferenceWidget3.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedServiceWidget13.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedBatteryWidget13.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedPSCSC200016Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedYourTransactionWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle24Widget9.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle38Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle20Widget8.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget9.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedGbeveAlbertWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle32Widget7.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedPayyourResitRegistrationWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedConfirmPaymentWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/Generated1011Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedPersonalDetailsWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage18resitnextpagewidget/generated/GeneratedRectangle1Widget13.dart';

/* Frame Page 18 Resit Next Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage18ResitNextPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget13(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget13(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget13(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget13()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget8(),
              ),
              Positioned(
                left: -4.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 648.0,
                child: GeneratedRectangle32Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle24Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 77.0,
                child: GeneratedRectangle37Widget6(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget8(),
              ),
              Positioned(
                left: 118.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 57.0,
                child: GeneratedConfirmPaymentWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget8(),
              ),
              Positioned(
                left: 139.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget9(),
              ),
              Positioned(
                left: 197.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle38Widget4(),
              ),
              Positioned(
                left: 9.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle39Widget1(),
              ),
              Positioned(
                left: 211.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget6(),
              ),
              Positioned(
                left: 103.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 19.0,
                child: GeneratedCancelWidget2(),
              ),
              Positioned(
                left: 13.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 17.0,
                child: GeneratedYourTransactionWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9386666666666666,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget57())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.050666666666666665,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget58())
                  ]);
                }),
              ),
              Positioned(
                left: 13.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 16.0,
                child: GeneratedPersonalDetailsWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedTransferWidget1(),
              ),
              Positioned(
                left: 254.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 19.0,
                child: GeneratedGH270000Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 16.0,
                child: GeneratedTOUCCResitAccountWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 16.0,
                child: GeneratedStudentNumberWidget1(),
              ),
              Positioned(
                left: 224.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 19.0,
                child: GeneratedPSCSC200016Widget5(),
              ),
              Positioned(
                left: 13.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 16.0,
                child: GeneratedStudentNameWidget1(),
              ),
              Positioned(
                left: 247.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 16.0,
                child: GeneratedGbeveAlbertWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 16.0,
                child: GeneratedTelNoWidget1(),
              ),
              Positioned(
                left: 262.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 19.0,
                child: Generated0256724911Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 19.0,
                child: Generated1011Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 19.0,
                child: GeneratedReferenceWidget3(),
              ),
              Positioned(
                left: 204.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 16.0,
                child: GeneratedResitRegistrationWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 21.0,
                child: GeneratedPayyourResitRegistrationWidget1(),
              )
            ]),
      ),
    ));
  }
}
