import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedYouhavesuccessfullypaidanamountofGH00aspaymentfor2022201.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedVectorWidget69.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedRectangle1Widget17.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedRectangle38Widget7.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedMaterialsymbolsreceiptlongroundedWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedVectorWidget71.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedServiceWidget17.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedPrintReceiptWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedWhatsAppImage20230314at20592Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedRectangle39Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedBatteryWidget17.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedRectangle32Widget11.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedDoneWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedYourtransactionwassuccessfulWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedTimeWidget17.dart';
import 'package:flutterapp/upayapp/generatedpage19resitsuccessfulwidget/generated/GeneratedRectangle40Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Page 19 Resit Successful
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage19ResitSuccessfulWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget17(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget17(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget17(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget17()),
              ),
              Positioned(
                left: -4.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 790.0,
                child: GeneratedRectangle32Widget11(),
              ),
              Positioned(
                left: 85.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 113.0,
                child: GeneratedYourtransactionwassuccessfulWidget1(),
              ),
              Positioned(
                left: 45.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 68.0,
                child:
                    GeneratedYouhavesuccessfullypaidanamountofGH00aspaymentfor2022201(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedWhatsAppImage20230314at20592Widget1(),
              ),
              Positioned(
                left: 145.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 85.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.312;
                  double scaleX = (constraints.maxWidth * percentWidth) / 117.0;

                  double percentHeight = 0.1440886699507389;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 117.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.344,
                        translateY: constraints.maxHeight * 0.16009852216748768,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget69())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 81.0,
                child: GeneratedRectangle40Widget3(),
              ),
              Positioned(
                left: 197.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle38Widget7(),
              ),
              Positioned(
                left: 9.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle39Widget5(),
              ),
              Positioned(
                left: 24.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMaterialsymbolsreceiptlongroundedWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9386666666666666,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget71())
                  ]);
                }),
              ),
              Positioned(
                left: 211.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 19.0,
                child: GeneratedDoneWidget1(),
              ),
              Positioned(
                left: 60.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 16.0,
                child: GeneratedPrintReceiptWidget1(),
              )
            ]),
      ),
    ));
  }
}
