import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedTimeWidget15.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedRectangle32Widget9.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedVectorWidget62.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedOopsAnerroroccuredWidget.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedYourrequestcouldnotbeprocessedatthistimePleasetryagainl.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedRectangle1Widget15.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget12.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedServiceWidget15.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedBatteryWidget15.dart';
import 'package:flutterapp/upayapp/generatedpage8paymentfailedpagewidget/generated/GeneratedRectangle39Widget3.dart';

/* Frame Page 8 Payment Failed Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage8PaymentFailedPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget15(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget15(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget15(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget15()),
              ),
              Positioned(
                left: -4.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 790.0,
                child: GeneratedRectangle32Widget9(),
              ),
              Positioned(
                left: 139.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget12(),
              ),
              Positioned(
                left: 9.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 51.0,
                child: GeneratedRectangle39Widget3(),
              ),
              Positioned(
                left: 49.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 19.0,
                child: GeneratedBackWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8186666666666667,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget62())
                  ]);
                }),
              ),
              Positioned(
                left: 94.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 76.0,
                child: GeneratedOopsAnerroroccuredWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 46.0,
                child:
                    GeneratedYourrequestcouldnotbeprocessedatthistimePleasetryagainl(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.304;

                  final double height =
                      constraints.maxHeight * 0.14039408866995073;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.33866666666666667,
                        y: constraints.maxHeight * 0.16009852216748768,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
