import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedPSCSC200016Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedGH270000Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget6.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle32Widget6.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedNextWidget5.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/Generated1011Widget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle37Widget5.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedStudentNumberWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedBatteryWidget12.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle1Widget12.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedServiceWidget12.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedVectorWidget54.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedReferenceWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedCancelWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedYourTransactionWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedSchoolFeesWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedUPAYWidget7.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedMaterialsymbolsarrowbackWidget7.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle20Widget7.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedConfirmPaymentWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedVectorWidget55.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedPayyourschoolFeesWidget1.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedGbeveAlbertWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedPersonalDetailsWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle24Widget8.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedTOUCCAdmissionAccountWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedTimeWidget12.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedRectangle38Widget3.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedTelNoWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedTransferWidget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/Generated0256724911Widget.dart';
import 'package:flutterapp/upayapp/generatedpage7paymentnextpagewidget/generated/GeneratedStudentNameWidget.dart';

/* Frame Page 7 Payment Next Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage7PaymentNextPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget12(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget12(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget12(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget12()),
              ),
              Positioned(
                left: 0.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedRectangle20Widget7(),
              ),
              Positioned(
                left: -4.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 648.0,
                child: GeneratedRectangle32Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle24Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 77.0,
                child: GeneratedRectangle37Widget5(),
              ),
              Positioned(
                left: 141.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 29.0,
                child: GeneratedUPAYWidget7(),
              ),
              Positioned(
                left: 40.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 25.0,
                child: GeneratedPayyourschoolFeesWidget1(),
              ),
              Positioned(
                left: 118.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 57.0,
                child: GeneratedConfirmPaymentWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget6(),
              ),
              Positioned(
                left: 139.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedMaterialsymbolsarrowbackWidget7(),
              ),
              Positioned(
                left: 197.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle38Widget3(),
              ),
              Positioned(
                left: 9.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 51.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 211.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget5(),
              ),
              Positioned(
                left: 103.0,
                top: 765.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 19.0,
                child: GeneratedCancelWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 17.0,
                child: GeneratedYourTransactionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9386666666666666,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget54())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.050666666666666665,
                        translateY: constraints.maxHeight * 0.9421182266009852,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget55())
                  ]);
                }),
              ),
              Positioned(
                left: 13.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 16.0,
                child: GeneratedPersonalDetailsWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 19.0,
                child: GeneratedTransferWidget(),
              ),
              Positioned(
                left: 254.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 19.0,
                child: GeneratedGH270000Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 16.0,
                child: GeneratedTOUCCAdmissionAccountWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 16.0,
                child: GeneratedStudentNumberWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 19.0,
                child: GeneratedPSCSC200016Widget4(),
              ),
              Positioned(
                left: 13.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 16.0,
                child: GeneratedStudentNameWidget(),
              ),
              Positioned(
                left: 247.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 16.0,
                child: GeneratedGbeveAlbertWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 16.0,
                child: GeneratedTelNoWidget(),
              ),
              Positioned(
                left: 262.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 19.0,
                child: Generated0256724911Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 19.0,
                child: Generated1011Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 19.0,
                child: GeneratedReferenceWidget2(),
              ),
              Positioned(
                left: 255.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 16.0,
                child: GeneratedSchoolFeesWidget(),
              )
            ]),
      ),
    ));
  }
}
