import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedVectorWidget80.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedRectangle1Widget21.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedRectangle32Widget15.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedEnterthephonenumberassociatedwithyouraccountandwellsend.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedServiceWidget21.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedResetPasswordWidget.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedVectorWidget79.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedTimeWidget21.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedEg0256Widget.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedRectangle40Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedBatteryWidget21.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/upayapp/generatedpage10forgotpasswordwidget/generated/GeneratedNextWidget8.dart';

/* Frame Page 10 Forgot Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage10ForgotPasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget21(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget21(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget21(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget21()),
              ),
              Positioned(
                left: 0.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedRectangle32Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.056,
                        translateY:
                            constraints.maxHeight * 0.059113300492610835,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget79())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 22.0,
                child: GeneratedResetPasswordWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 47.0,
                child:
                    GeneratedEnterthephonenumberassociatedwithyouraccountandwellsend(),
              ),
              Positioned(
                left: 21.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 17.0,
                child: GeneratedPhoneNumberWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 17.0,
                child: GeneratedEg0256Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 51.0,
                child: GeneratedRectangle40Widget7(),
              ),
              Positioned(
                left: 34.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 19.0,
                child: GeneratedNextWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.020935960591133004;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8773333333333333,
                        translateY: constraints.maxHeight * 0.937192118226601,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget80())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
