import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedEnterOTPWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedWevesentyoua4digitcodetoWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedVectorWidget21.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedServiceWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedCANCELPROCESSWidget.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/Generated4911Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedVectorWidget22.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedTimeWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedVectorWidget23.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedCancelWidget.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedBycancellingtheprocessyouwilllosealltheinformationyouen.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedBatteryWidget4.dart';
import 'package:flutterapp/upayapp/generatedpage4otpcancelpagewidget/generated/GeneratedRectangle12Widget2.dart';

/* Frame Page 4 OTP Cancel Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage4OTPCancelPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget4(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget4(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget4()),
              ),
              Positioned(
                left: 0.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedRectangle12Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02586206896551724;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 21.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.912,
                        translateY: constraints.maxHeight * 0.07019704433497537,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget21())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.056,
                        translateY: constraints.maxHeight * 0.06896551724137931,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget22())
                  ]);
                }),
              ),
              Positioned(
                left: 13.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 26.0,
                child: GeneratedEnterOTPWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 22.0,
                child: GeneratedWevesentyoua4digitcodetoWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 26.0,
                child: Generated4911Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 110.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 200.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 290.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 2.0,
                child: GeneratedRectangle16Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 780.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 257.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.037333333333333336;
                  double scaleX = (constraints.maxWidth * percentWidth) / 14.0;

                  double percentHeight = 0.017241379310344827;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 14.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.848,
                        translateY: constraints.maxHeight * 0.3731527093596059,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget23())
                  ]);
                }),
              ),
              Positioned(
                left: 35.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 27.0,
                child: GeneratedCancelWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 76.0,
                child:
                    GeneratedBycancellingtheprocessyouwilllosealltheinformationyouen(),
              ),
              Positioned(
                left: 34.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 48.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 18.0,
                child: GeneratedCANCELPROCESSWidget(),
              )
            ]),
      ),
    ));
  }
}
