import 'package:flutter/material.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEgPSCSC200000Widget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedTimeWidget24.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedServiceWidget24.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle42Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEgDoeWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedSIGNUPWidget2.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEnteryourLastNameWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedAlreadyhaveanaccountLoginWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEg0256Widget1.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEnteryourPhoneNumberWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedBatteryWidget24.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle1Widget24.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEnteryourOtherNamesWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedCreateanAccountforfreeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle32Widget18.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEgJohnWidget.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedRectangle41Widget3.dart';
import 'package:flutterapp/upayapp/generatedpage14signuppagewidget/generated/GeneratedEnteryourRegistrationNumberWidget.dart';

/* Frame Page 14 Sign Up Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage14SignUpPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 16.0,
                child: GeneratedRectangle1Widget24(),
              ),
              Positioned(
                left: 282.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.5,
                height: 12.0,
                child: GeneratedServiceWidget24(),
              ),
              Positioned(
                left: null,
                top: 2.0,
                right: 12.5,
                bottom: null,
                width: 26.5,
                height: 11.5,
                child: GeneratedBatteryWidget24(),
              ),
              Positioned(
                left: null,
                top: 4.0,
                right: null,
                bottom: null,
                width: 31.8046875,
                height: 8.876953125,
                child: TransformHelper.translate(
                    x: -158.60, y: 0.00, z: 0, child: GeneratedTimeWidget24()),
              ),
              Positioned(
                left: 0.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 72.0,
                child: GeneratedRectangle32Widget18(),
              ),
              Positioned(
                left: 121.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 26.0,
                child: GeneratedSignUpWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 19.0,
                child: GeneratedCreateanAccountforfreeWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 17.0,
                child: GeneratedEnteryourLastNameWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 17.0,
                child: GeneratedEnteryourOtherNamesWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 17.0,
                child: GeneratedEnteryourRegistrationNumberWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 17.0,
                child: GeneratedEnteryourPhoneNumberWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 17.0,
                child: GeneratedAlreadyhaveanaccountLoginWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle41Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle42Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 17.0,
                child: GeneratedEgDoeWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedEgJohnWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 17.0,
                child: GeneratedEgPSCSC200000Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 17.0,
                child: GeneratedEg0256Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 40.0,
                child: GeneratedRectangle11Widget2(),
              ),
              Positioned(
                left: 135.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 21.0,
                child: GeneratedSIGNUPWidget2(),
              )
            ]),
      ),
    ));
  }
}
